server:
  port: 8080
  servlet:
    context-path: /techadict

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/techadict"
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "abCDefGhijkLMnopQRstUvwxYZ0123456789!@#$$%hs512LongSecretKeyExample987654321"